name: CPP_CI
[span_1](start_span)on: [push] # Trigger[span_1](end_span)

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        [span_2](start_span)run: g++ main.cpp -o app_test # Stage: Сборка[span_2](end_span)
        
      - name: Test
        [span_3](start_span)[span_4](start_span)run: ./app_test # Stage: Тесты[span_3](end_span)[span_4](end_span)
